plugins {
	id 'fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id 'gradle-build-utils' version '1.7.0'
}

Properties props = buildUtils.loadProperties('publish.properties')  // will be empty, if the file is missing

version = "${project.mod_version}+${project.minecraft_version}"
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven {
        url "https://repo.lclpnet.work/repository/internal"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:$minecraft_version"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:$loader_version"

    modImplementation "net.fabricmc.fabric-api:fabric-api:$fabric_version"
    include modImplementation("work.lclpnet.mods.kibu:kibu-hook-api:$kibu_hook_api_version")

    // libbulletjme JVM library
    include api("com.github.stephengold:Libbulletjme-Linux64:$libbulletjme_version")

    // libbulletjme native libraries
    /* JME flavors:
     * Sp (single-precision arithmetic)
     * SpMt (single-precision arithmetic, multithreaded), unsupported on MacOSX
     * Dp (double-precision arithmetic)
     * DpMt (double-precision arithmetic, multithreaded), unsupported on MacOSX
     */
    include(runtimeOnly("com.github.stephengold:Libbulletjme-Linux64:$libbulletjme_version:SpMtRelease"))
    include(runtimeOnly("com.github.stephengold:Libbulletjme-Linux_ARM64:$libbulletjme_version:SpMtRelease"))
    include(runtimeOnly("com.github.stephengold:Libbulletjme-Windows64:$libbulletjme_version:SpMtRelease"))
    include(runtimeOnly("com.github.stephengold:Libbulletjme-MacOSX64:$libbulletjme_version:SpRelease"))
    include(runtimeOnly("com.github.stephengold:Libbulletjme-MacOSX_ARM64:$libbulletjme_version:SpRelease"))

    // for platform-specific native library loading
    include(implementation("io.github.electrostat-lab:snaploader:1.0.0-stable"))
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release.set(21)
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.base.archivesName.get()}"}
	}
}

// configure the maven publication
publishing {
    publications {
        create('mavenJava', MavenPublication) {
            artifactId = project.base.archivesName.get()

            from components.java

            pom {
                name = 'kibu-physics'
                description = 'A physics simulation API for Fabric'
            }
        }
    }

    // automatically use DEPLOY_URL, DEPLOY_USER and DEPLOY_PASSWORD environment variables
    // or mavenHost, mavenUser and mavenPassword from props
    buildUtils.setupPublishRepository(repositories, props)
}