# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.7
loader_version=0.16.14
loom_version=1.11-SNAPSHOT
mod_version=0.1.0

# Mod Properties
maven_group=work.lclpnet.mods.kibu
archives_base_name=kibu-physics

# Dependencies
fabric_version=0.129.0+1.21.7
kibu_hook_api_version=1.4.0
kibu_access_lib_version=0.16.0+1.21.7

libbulletjme_version=22.0.1