package dev.lazurite.rayon.api.event.collision;

import dev.lazurite.rayon.api.PhysicsElement;
import dev.lazurite.rayon.impl.bullet.collision.body.ElementRigidBody;
import dev.lazurite.rayon.impl.bullet.collision.body.TerrainRigidBody;
import work.lclpnet.kibu.hook.Hook;
import work.lclpnet.kibu.hook.HookFactory;

/**
 * @since 1.0.0
 */
public class ElementCollisionEvents {

    public static final Hook<BlockCollision> BLOCK_COLLISION = HookFactory.createArrayBacked(BlockCollision.class, hooks -> (element, terrainObject, impulse) -> {
        for (BlockCollision hook : hooks) {
            hook.onCollide(element, terrainObject, impulse);
        }
    });

    public static final Hook<BlockCollision> FLUID_COLLISION = HookFactory.createArrayBacked(BlockCollision.class, hooks -> (element, terrainObject, impulse) -> {
        for (BlockCollision hook : hooks) {
            hook.onCollide(element, terrainObject, impulse);
        }
    });

    public static final Hook<ElementCollision> ELEMENT_COLLISION = HookFactory.createArrayBacked(ElementCollision.class, hooks -> (element1, element2, impulse) -> {
        for (ElementCollision hook : hooks) {
            hook.onCollide(element1, element2, impulse);
        }
    });

    private ElementCollisionEvents() { }

    @FunctionalInterface
    public interface BlockCollision {
        /**
         * Invoked each time an {@link ElementRigidBody} collides with a {@link }.
         * @param element the element
         * @param terrainObject the terrain object
         * @param impulse the impulse generated by the collision
         */
        void onCollide(PhysicsElement<?> element, TerrainRigidBody terrainObject, float impulse);
    }

    @FunctionalInterface
    public interface FluidCollision {
        /**
         * Invoked each time an {@link ElementRigidBody} collides with a {@link TerrainRigidBody}.
         * @param element the element
         * @param terrainObject the terrain object
         * @param impulse the impulse generated by the collision
         */
        void onCollide(PhysicsElement<?> element, TerrainRigidBody terrainObject, float impulse);
    }

    @FunctionalInterface
    public interface ElementCollision {
        /**
         * Invoked each time an {@link ElementRigidBody} collides with another {@link ElementRigidBody}.
         * @param element1 the first element
         * @param element2 the second element
         * @param impulse the impulse generated by the collision
         */
        void onCollide(PhysicsElement<?> element1, PhysicsElement<?> element2, float impulse);
    }
}
